version: "3"
services:
  todo-backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - target: 8080
        published: 8080
  todo-frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - target: 5050
        published: 5050