name: test todo, and build and push docker image

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]

jobs:

  build_todo:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: install golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: run tests
      run: |
        cd backend
        go test *.go
    
    - name: build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ahmedsalahucf/todo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}